-- Batch 0 disposable staging fixtures — APPLIED 2026-10-05 via operator/agent seed.
-- Owners (Auth users, confirmed in Supabase Auth UI):
--   A: batch0.fixture.a@almona.local  1dfae5b1-5299-4737-b1a4-d1bc640950db
--   B: batch0.fixture.b@almona.local  7c4aa1d9-cbf4-4887-aca3-5a85e0d72df7
-- Passwords: see local gitignored .env.batch0.fixtures (never commit).
--
-- Restore (staging only):
--   DELETE FROM public.fabricator_positions_v2 WHERE meta->>'fixture_tag' = 'batch0-2026-10-05';
--   DELETE FROM public.fabricator_projects_v2  WHERE meta->>'fixture_tag' = 'batch0-2026-10-05';
--   DELETE FROM public.fabricator_profiles     WHERE specifications->>'fixture_tag' = 'batch0-2026-10-05';
--   -- Auth users can remain for reuse, or delete in Auth dashboard.

-- Seed already applied live. This file documents the matrix for re-runs:
--   Owner A: project BATCH0-A, poses POS-R1 (qc_revision=1) + POS-R2 (qc_revision=2)
--   Owner A: populated frame stock + empty stock profile
--   Owner B: project BATCH0-B, pose POS-001 (cross-owner reject target)
--   Materials: aluminum + UPVC tagged fixture_tag=batch0-2026-10-05
