/**
 * Certification Document Generation and Management
 * Manages compliance certificates and documentation
 */

import { EN14351ComplianceResult } from './EN14351';
import { ASTME1300ComplianceResult } from './ASTME1300';
import { QualityAudit } from './QualityAudit';

export interface Certificate {
  id: string;
  projectId: string;
  certificateNumber: string;
  type: 'EN14351' | 'ASTME1300' | 'quality' | 'custom';
  issueDate: Date;
  expiryDate?: Date;
  status: 'active' | 'expired' | 'revoked';
  documentUrl?: string;
  metadata: Record<string, unknown>;
}

export interface CertificateTemplate {
  id: string;
  name: string;
  type: Certificate['type'];
  template: string; // HTML or markdown template
  fields: string[];
}

export class CertificationManager {
  private certificates: Map<string, Certificate[]> = new Map();
  private templates: Map<string, CertificateTemplate> = new Map();

  constructor() {
    this.initializeTemplates();
  }

  /**
   * Generate certificate from compliance result
   */
  generateCertificate(
    projectId: string,
    type: Certificate['type'],
    result: EN14351ComplianceResult | ASTME1300ComplianceResult | QualityAudit
  ): Certificate {
    let certificateNumber: string;
    let expiryDate: Date | undefined;

    if (type === 'EN14351' && 'compliant' in result) {
      const enResult = result as EN14351ComplianceResult;
      certificateNumber = enResult.certification.certificateNumber || '';
      expiryDate = enResult.certification.expiryDate;
    } else if (type === 'ASTME1300' && 'compliant' in result) {
      const astmResult = result as ASTME1300ComplianceResult;
      certificateNumber = astmResult.certification.certificateNumber || '';
      expiryDate = astmResult.certification.expiryDate;
    } else {
      certificateNumber = `CERT-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
    }

    const certificate: Certificate = {
      id: `cert_${Date.now()}`,
      projectId,
      certificateNumber,
      type,
      issueDate: new Date(),
      expiryDate,
      status: 'active',
      metadata: {
        result,
      },
    };

    // Store certificate
    const projectCerts = this.certificates.get(projectId) || [];
    projectCerts.push(certificate);
    this.certificates.set(projectId, projectCerts);

    return certificate;
  }

  /**
   * Get certificates for project
   */
  getCertificates(projectId: string): Certificate[] {
    return this.certificates.get(projectId) || [];
  }

  /**
   * Get active certificates
   */
  getActiveCertificates(projectId: string): Certificate[] {
    const now = new Date();
    return this.getCertificates(projectId).filter(
      (c) => c.status === 'active' && (!c.expiryDate || c.expiryDate > now)
    );
  }

  /**
   * Revoke certificate
   */
  revokeCertificate(projectId: string, certificateId: string): boolean {
    const certificates = this.certificates.get(projectId);
    if (!certificates) return false;

    const certificate = certificates.find((c) => c.id === certificateId);
    if (!certificate) return false;

    certificate.status = 'revoked';
    return true;
  }

  /**
   * Check for expired certificates
   */
  checkExpiredCertificates(): Certificate[] {
    const now = new Date();
    const expired: Certificate[] = [];

    for (const certificates of this.certificates.values()) {
      for (const cert of certificates) {
        if (
          cert.status === 'active' &&
          cert.expiryDate &&
          cert.expiryDate <= now
        ) {
          cert.status = 'expired';
          expired.push(cert);
        }
      }
    }

    return expired;
  }

  /**
   * Generate certificate document
   */
  generateDocument(certificate: Certificate): string {
    const template = this.templates.get(certificate.type);
    if (!template) {
      return this.generateDefaultDocument(certificate);
    }

    // In real implementation, this would use a template engine
    return this.generateDefaultDocument(certificate);
  }

  /**
   * Generate default certificate document
   */
  private generateDefaultDocument(certificate: Certificate): string {
    return `
CERTIFICATE OF COMPLIANCE
Certificate Number: ${certificate.certificateNumber}
Type: ${certificate.type}
Issue Date: ${certificate.issueDate.toLocaleDateString()}
${certificate.expiryDate ? `Expiry Date: ${certificate.expiryDate.toLocaleDateString()}` : ''}
Status: ${certificate.status.toUpperCase()}

Project ID: ${certificate.projectId}

This certificate confirms compliance with applicable standards and regulations.

Generated by Almona Portfolio Forge Certification System
    `.trim();
  }

  /**
   * Initialize certificate templates
   */
  private initializeTemplates(): void {
    this.templates.set('EN14351', {
      id: 'en14351_template',
      name: 'EN 14351 Certificate Template',
      type: 'EN14351',
      template: '',
      fields: ['certificateNumber', 'issueDate', 'expiryDate', 'complianceScore'],
    });

    this.templates.set('ASTME1300', {
      id: 'astme1300_template',
      name: 'ASTM E1300 Certificate Template',
      type: 'ASTME1300',
      template: '',
      fields: ['certificateNumber', 'issueDate', 'expiryDate', 'complianceScore'],
    });

    this.templates.set('quality', {
      id: 'quality_template',
      name: 'Quality Certificate Template',
      type: 'quality',
      template: '',
      fields: ['certificateNumber', 'issueDate', 'overallScore', 'status'],
    });
  }

  /**
   * Export certificate as PDF (placeholder)
   */
  exportToPDF(certificate: Certificate): string {
    // In real implementation, this would generate a PDF
    return this.generateDocument(certificate);
  }
}

