import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/shared/ui/ui/dialog';
import { Button } from '@/shared/ui/ui/button';
import { RadioGroup, RadioGroupItem } from '@/shared/ui/ui/radio-group';
import { Label } from '@/shared/ui/ui/label';
import { Badge } from '@/shared/ui/ui/badge';
import { Card, CardContent } from '@/shared/ui/ui/card';
import { yilmazMachines } from '@/constants/productsData';
import { Machine } from '@/types';
import ProductCard from '@/shared/ui/ui/ProductCard';
import { useQuote } from '@/context/QuoteContext';
import { useToast } from '@/hooks/useToast';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Settings, 
  Zap, 
  Target, 
  CheckCircle, 
  ArrowRight, 
  ArrowLeft,
  Building2,
  Square,
  Wrench,
  Cpu,
  Sparkles,
  Award,
  TrendingUp,
  Download,
  ShoppingCart,
  FileText,
  Printer
} from 'lucide-react';

interface MachineRecommendationWizardProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

type Step = 'material' | 'application' | 'automation' | 'production' | 'results';

interface WizardAnswers {
  material: string;
  application: string;
  automation: string;
  production: string;
}

const MachineRecommendationWizard: React.FC<MachineRecommendationWizardProps> = ({ open, onOpenChange }) => {
  const [step, setStep] = useState<Step>('material');
  const [answers, setAnswers] = useState<WizardAnswers>({ 
    material: '', 
    application: '', 
    automation: '',
    production: ''
  });
  const [recommendations, setRecommendations] = useState<Machine[]>([]);
  const { addToQuote } = useQuote();
  const { toast } = useToast();

  const steps = [
    { id: 'material', title: 'Material Type', icon: Building2 },
    { id: 'application', title: 'Application', icon: Square },
    { id: 'automation', title: 'Automation Level', icon: Cpu },
    { id: 'production', title: 'Production Scale', icon: TrendingUp },
    { id: 'results', title: 'Recommendations', icon: Award }
  ];

  const currentStepIndex = steps.findIndex(s => s.id === step);

  // Helper function to download PDF specs
  const handleDownloadSpecs = (machine: Machine) => {
    if (machine.specPdf) {
      // Create a temporary link to download the PDF
      const link = document.createElement('a');
      link.href = machine.specPdf;
      link.download = `${machine.name.replace(/\s+/g, '_')}_specs.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      toast({
        title: "Download Started",
        description: `Downloading specifications for ${machine.name}`,
      });
    } else {
      toast({
        title: "No Specifications Available",
        description: "Specifications are not available for this machine",
        variant: "destructive"
      });
    }
  };

  // Helper function to add machine to quote
  const handleAddToQuote = (machine: Machine) => {
    const shopProduct = {
      id: machine.id,
      name: machine.name,
      description: machine.description,
      imageUrl: machine.imageUrl,
      category: machine.category,
      tags: machine.tags || [],
      stock: 0, // Default stock
      pricing: {
        base: 0,
        currency: 'EGP',
        tax: 0
      }
    };
    
    addToQuote(shopProduct);
    toast({
      title: "Added to Quote",
      description: `${machine.name} has been added to your quote`,
    });
  };

  // Helper function to export summary as PDF
  const handleExportSummary = () => {
    const summaryData = {
      material: answers.material,
      application: answers.application,
      automation: answers.automation,
      production: answers.production,
      recommendations: recommendations.map(m => ({
        name: m.name,
        description: m.description,
        category: m.category
      })),
      timestamp: new Date().toISOString()
    };

    // Create a simple text-based summary for now
    const summaryText = `
MACHINE RECOMMENDATION SUMMARY
Generated: ${new Date().toLocaleDateString()}

SELECTIONS:
- Material: ${answers.material}
- Application: ${answers.application}
- Automation: ${answers.automation}
- Production Scale: ${answers.production}

RECOMMENDED MACHINES:
${recommendations.map((m, i) => `${i + 1}. ${m.name} - ${m.description}`).join('\n')}

This summary was generated by the Almona Machine Recommendation Wizard.
    `.trim();

    // Create and download the summary as a text file
    const blob = new Blob([summaryText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `machine_recommendation_summary_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast({
      title: "Summary Exported",
      description: "Your recommendation summary has been downloaded",
    });
  };

  const handleValueChange = (key: keyof typeof answers, value: string) => {
    setAnswers(prev => {
      const newAnswers = { ...prev, [key]: value };
      
      // Smart reset: If material changes, clear application selection
      if (key === 'material') {
        newAnswers.application = '';
      }
      
      // Smart reset: If application changes, clear automation selection
      if (key === 'application') {
        newAnswers.automation = '';
      }
      
      return newAnswers;
    });
  };

  const getRecommendations = () => {
    let filtered = yilmazMachines;

    // Material-based filtering
    if (answers.material === 'aluminum') {
      filtered = filtered.filter(m => 
        m.tags?.some(tag => tag.toLowerCase().includes('aluminum')) ||
        m.name.toLowerCase().includes('aluminum') ||
        m.category.includes('aluminum') ||
        m.category.includes('cutting') ||
        m.category.includes('crimping')
      );
    } else if (answers.material === 'upvc') {
      filtered = filtered.filter(m => 
        m.tags?.some(tag => tag.toLowerCase().includes('pvc') || tag.toLowerCase().includes('upvc')) ||
        m.name.toLowerCase().includes('pvc') ||
        m.category.includes('pvc') ||
        m.category.includes('welding') ||
        m.category.includes('cutting')
      );
    } else if (answers.material === 'both') {
      // For both materials, show machines that can handle either
      filtered = filtered.filter(m => 
        m.tags?.some(tag => 
          tag.toLowerCase().includes('aluminum') || 
          tag.toLowerCase().includes('pvc') || 
          tag.toLowerCase().includes('upvc')
        ) ||
        m.name.toLowerCase().includes('aluminum') ||
        m.name.toLowerCase().includes('pvc') ||
        m.category.includes('cutting') ||
        m.category.includes('welding') ||
        m.category.includes('processing')
      );
    }

    // Application-based filtering
    if (answers.application) {
      if (answers.application === 'cutting-machines') {
        filtered = filtered.filter(m => 
          m.category.includes('cutting') || 
          m.name.toLowerCase().includes('cutting') ||
          m.tags?.some(tag => tag.toLowerCase().includes('cutting'))
        );
      } else if (answers.application === 'welding-machines') {
        filtered = filtered.filter(m => 
          m.category.includes('welding') || 
          m.name.toLowerCase().includes('welding') ||
          m.tags?.some(tag => tag.toLowerCase().includes('welding'))
        );
      } else if (answers.application === 'crimping-machines') {
        filtered = filtered.filter(m => 
          m.category.includes('crimping') || 
          m.name.toLowerCase().includes('crimping') ||
          m.tags?.some(tag => tag.toLowerCase().includes('crimping'))
        );
      } else if (answers.application === 'glazing-bead') {
        filtered = filtered.filter(m => 
          m.category.includes('glazing') || 
          m.name.toLowerCase().includes('glazing') ||
          m.name.toLowerCase().includes('bead') ||
          m.tags?.some(tag => 
            tag.toLowerCase().includes('glazing') || 
            tag.toLowerCase().includes('bead')
          )
        );
      } else if (answers.application === 'end-milling') {
        filtered = filtered.filter(m => 
          m.category.includes('end-milling') || 
          m.name.toLowerCase().includes('end-milling') ||
          m.name.toLowerCase().includes('end milling') ||
          m.tags?.some(tag => 
            tag.toLowerCase().includes('end-milling') || 
            tag.toLowerCase().includes('end milling')
          )
        );
      } else if (answers.application === 'cleaning') {
        filtered = filtered.filter(m => 
          m.category.includes('cleaning') || 
          m.name.toLowerCase().includes('cleaning') ||
          m.tags?.some(tag => tag.toLowerCase().includes('cleaning'))
        );
      } else if (answers.application === 'processing-centers') {
        filtered = filtered.filter(m => 
          m.category.includes('processing') || 
          m.category.includes('milling') ||
          m.name.toLowerCase().includes('milling') ||
          m.name.toLowerCase().includes('drilling') ||
          m.tags?.some(tag => 
            tag.toLowerCase().includes('milling') || 
            tag.toLowerCase().includes('drilling') ||
            tag.toLowerCase().includes('processing')
          )
        );
      }
    }

    // Automation-based filtering
    if (answers.automation) {
      if (answers.automation === 'cnc') {
        filtered = filtered.filter(m => 
          m.tags?.includes('CNC') || 
          m.type.includes('CNC') ||
          m.name.toLowerCase().includes('cnc')
        );
      } else if (answers.automation === 'automatic') {
        filtered = filtered.filter(m => 
          m.tags?.includes('Automatic') || 
          m.type.includes('Automatic') ||
          m.name.toLowerCase().includes('automatic')
        );
      } else if (answers.automation === 'manual') {
        filtered = filtered.filter(m => 
          !m.tags?.includes('CNC') && 
          !m.tags?.includes('Automatic') &&
          !m.name.toLowerCase().includes('cnc') &&
          !m.name.toLowerCase().includes('automatic')
        );
      }
    }

    // Production scale filtering
    if (answers.production === 'high-volume') {
      filtered = filtered.filter(m => 
        m.tags?.includes('High Volume') || 
        m.tags?.includes('Production Line') ||
        m.name.toLowerCase().includes('production') ||
        m.name.toLowerCase().includes('line')
      );
    } else if (answers.production === 'small-scale') {
      filtered = filtered.filter(m => 
        m.tags?.includes('Small Scale') || 
        m.tags?.includes('Manual') ||
        m.name.toLowerCase().includes('manual') ||
        m.name.toLowerCase().includes('small')
      );
    }

    setRecommendations(filtered);
    setStep('results');
  };

  const resetWizard = () => {
    setStep('material');
    setAnswers({ material: '', application: '', automation: '', production: '' });
    setRecommendations([]);
  };

  const nextStep = () => {
    const nextIndex = currentStepIndex + 1;
    if (nextIndex < steps.length - 1) {
      setStep(steps[nextIndex].id as Step);
    } else {
      getRecommendations();
    }
  };

  const prevStep = () => {
    const prevIndex = currentStepIndex - 1;
    if (prevIndex >= 0) {
      setStep(steps[prevIndex].id as Step);
    }
  };

  const renderStep = () => {
    switch (step) {
      case 'material':
        return (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="space-y-6"
          >
            <div className="text-center">
              <Building2 className="h-10 w-10 sm:h-12 sm:w-12 text-almona-orange mx-auto mb-4" />
              <h3 className="text-xl sm:text-2xl font-bold mb-2">Choose Your Material</h3>
              <p className="text-gray-400 text-sm sm:text-base">What material will you be working with for windows and doors?</p>
            </div>
            <RadioGroup value={answers.material} onValueChange={(v) => handleValueChange('material', v)}>
              <div className="grid gap-3 sm:gap-4">
                <Card 
                  className={`cursor-pointer transition-all ${answers.material === 'aluminum' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('material', 'aluminum')}
                >
                  <CardContent className="p-3 sm:p-4">
                    <div className="flex items-start space-x-3 sm:space-x-4">
                      <RadioGroupItem value="aluminum" id="aluminum" className="mt-1" />
                      <div className="flex-1 min-w-0">
                        <Label htmlFor="aluminum" className="text-base sm:text-lg font-semibold cursor-pointer">Aluminum</Label>
                        <p className="text-xs sm:text-sm text-gray-400 mt-1">Lightweight, durable, and corrosion-resistant for modern window and door systems</p>
                        <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                          <Badge variant="secondary" className="text-xs">High Strength</Badge>
                          <Badge variant="secondary" className="text-xs">Weather Resistant</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card 
                  className={`cursor-pointer transition-all ${answers.material === 'upvc' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('material', 'upvc')}
                >
                  <CardContent className="p-3 sm:p-4">
                    <div className="flex items-start space-x-3 sm:space-x-4">
                      <RadioGroupItem value="upvc" id="upvc" className="mt-1" />
                      <div className="flex-1 min-w-0">
                        <Label htmlFor="upvc" className="text-base sm:text-lg font-semibold cursor-pointer">UPVC</Label>
                        <p className="text-xs sm:text-sm text-gray-400 mt-1">Energy-efficient, low maintenance, and excellent thermal insulation properties</p>
                        <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                          <Badge variant="secondary" className="text-xs">Energy Efficient</Badge>
                          <Badge variant="secondary" className="text-xs">Low Maintenance</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card 
                  className={`cursor-pointer transition-all ${answers.material === 'both' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('material', 'both')}
                >
                  <CardContent className="p-3 sm:p-4">
                    <div className="flex items-start space-x-3 sm:space-x-4">
                      <RadioGroupItem value="both" id="both" className="mt-1" />
                      <div className="flex-1 min-w-0">
                        <Label htmlFor="both" className="text-base sm:text-lg font-semibold cursor-pointer">Both Materials</Label>
                        <p className="text-xs sm:text-sm text-gray-400 mt-1">Versatile production line handling both aluminum and UPVC materials</p>
                        <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                          <Badge variant="secondary" className="text-xs">Versatile</Badge>
                          <Badge variant="secondary" className="text-xs">Multi-Material</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </RadioGroup>
          </motion.div>
        );
      case 'application':
        const isAluminum = answers.material === 'aluminum';
        const isUPVC = answers.material === 'upvc';
        const isBoth = answers.material === 'both';
        
        return (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="space-y-6"
          >
            <div className="text-center">
              <Square className="h-10 w-10 sm:h-12 sm:w-12 text-almona-orange mx-auto mb-4" />
              <h3 className="text-xl sm:text-2xl font-bold mb-2">Primary Application</h3>
              <p className="text-gray-400 text-sm sm:text-base">
                {isAluminum && "What aluminum processing do you need?"}
                {isUPVC && "What UPVC processing do you need?"}
                {isBoth && "What is your main manufacturing focus?"}
              </p>
            </div>
            <RadioGroup value={answers.application} onValueChange={(v) => handleValueChange('application', v)}>
              <div className="grid gap-3 sm:gap-4">
                <Card 
                  className={`cursor-pointer transition-all ${answers.application === 'cutting-machines' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('application', 'cutting-machines')}
                >
                  <CardContent className="p-3 sm:p-4">
                    <div className="flex items-start space-x-3 sm:space-x-4">
                      <RadioGroupItem value="cutting-machines" id="cutting" className="mt-1" />
                      <div className="flex-1 min-w-0">
                        <Label htmlFor="cutting" className="text-base sm:text-lg font-semibold cursor-pointer">Profile Cutting</Label>
                        <p className="text-xs sm:text-sm text-gray-400 mt-1">
                          {isAluminum && "Precise cutting of aluminum profiles for window and door frames"}
                          {isUPVC && "Precise cutting of UPVC profiles for window and door frames"}
                          {isBoth && "Precise cutting of aluminum and UPVC profiles for window and door frames"}
                        </p>
                        <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                          <Badge variant="secondary" className="text-xs">Precision Cutting</Badge>
                          <Badge variant="secondary" className="text-xs">Angle Cutting</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                
                {/* Only show Corner Welding for UPVC or Both materials */}
                {(isUPVC || isBoth) && (
                  <Card 
                    className={`cursor-pointer transition-all ${answers.application === 'welding-machines' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                    onClick={() => handleValueChange('application', 'welding-machines')}
                  >
                    <CardContent className="p-3 sm:p-4">
                      <div className="flex items-start space-x-3 sm:space-x-4">
                        <RadioGroupItem value="welding-machines" id="welding" className="mt-1" />
                        <div className="flex-1 min-w-0">
                          <Label htmlFor="welding" className="text-base sm:text-lg font-semibold cursor-pointer">Corner Welding</Label>
                          <p className="text-xs sm:text-sm text-gray-400 mt-1">
                            {isUPVC && "Four-head welding machines for seamless UPVC frame assembly"}
                            {isBoth && "Four-head welding machines for seamless UPVC frame assembly"}
                          </p>
                          <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                            <Badge variant="secondary" className="text-xs">Four-Head Welding</Badge>
                            <Badge variant="secondary" className="text-xs">Seamless Joints</Badge>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Show UPVC-specific applications */}
                {isUPVC && (
                  <>
                    <Card 
                      className={`cursor-pointer transition-all ${answers.application === 'glazing-bead' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                      onClick={() => handleValueChange('application', 'glazing-bead')}
                    >
                      <CardContent className="p-3 sm:p-4">
                        <div className="flex items-start space-x-3 sm:space-x-4">
                          <RadioGroupItem value="glazing-bead" id="glazing-bead" className="mt-1" />
                          <div className="flex-1 min-w-0">
                            <Label htmlFor="glazing-bead" className="text-base sm:text-lg font-semibold cursor-pointer">Glazing Bead Processing</Label>
                            <p className="text-xs sm:text-sm text-gray-400 mt-1">Cutting and processing glazing beads to secure glass panes within UPVC frames</p>
                            <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                              <Badge variant="secondary" className="text-xs">Glass Securing</Badge>
                              <Badge variant="secondary" className="text-xs">Bead Cutting</Badge>
                            </div>
                          </div>
                        </div>
                      </CardContent>
                    </Card>

                    <Card 
                      className={`cursor-pointer transition-all ${answers.application === 'end-milling' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                      onClick={() => handleValueChange('application', 'end-milling')}
                    >
                      <CardContent className="p-3 sm:p-4">
                        <div className="flex items-start space-x-3 sm:space-x-4">
                          <RadioGroupItem value="end-milling" id="end-milling" className="mt-1" />
                          <div className="flex-1 min-w-0">
                            <Label htmlFor="end-milling" className="text-base sm:text-lg font-semibold cursor-pointer">End Milling</Label>
                            <p className="text-xs sm:text-sm text-gray-400 mt-1">Precise end milling of UPVC profiles to prepare ends for assembly</p>
                            <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                              <Badge variant="secondary" className="text-xs">Profile Preparation</Badge>
                              <Badge variant="secondary" className="text-xs">Assembly Ready</Badge>
                            </div>
                          </div>
                        </div>
                      </CardContent>
                    </Card>

                    <Card 
                      className={`cursor-pointer transition-all ${answers.application === 'cleaning' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                      onClick={() => handleValueChange('application', 'cleaning')}
                    >
                      <CardContent className="p-3 sm:p-4">
                        <div className="flex items-start space-x-3 sm:space-x-4">
                          <RadioGroupItem value="cleaning" id="cleaning" className="mt-1" />
                          <div className="flex-1 min-w-0">
                            <Label htmlFor="cleaning" className="text-base sm:text-lg font-semibold cursor-pointer">Corner Cleaning</Label>
                            <p className="text-xs sm:text-sm text-gray-400 mt-1">Cleaning machines to remove excess material and ensure smooth finish after welding</p>
                            <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                              <Badge variant="secondary" className="text-xs">Post-Welding</Badge>
                              <Badge variant="secondary" className="text-xs">Smooth Finish</Badge>
                            </div>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </>
                )}
                
                {/* Show Corner Crimping for Aluminum */}
                {isAluminum && (
                  <Card 
                    className={`cursor-pointer transition-all ${answers.application === 'crimping-machines' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                    onClick={() => handleValueChange('application', 'crimping-machines')}
                  >
                    <CardContent className="p-3 sm:p-4">
                      <div className="flex items-start space-x-3 sm:space-x-4">
                        <RadioGroupItem value="crimping-machines" id="crimping" className="mt-1" />
                        <div className="flex-1 min-w-0">
                          <Label htmlFor="crimping" className="text-base sm:text-lg font-semibold cursor-pointer">Corner Crimping</Label>
                          <p className="text-xs sm:text-sm text-gray-400 mt-1">Corner crimping machines for aluminum frame assembly</p>
                          <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                            <Badge variant="secondary" className="text-xs">Corner Crimping</Badge>
                            <Badge variant="secondary" className="text-xs">Aluminum Assembly</Badge>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )}
                
                <Card 
                  className={`cursor-pointer transition-all ${answers.application === 'processing-centers' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('application', 'processing-centers')}
                >
                  <CardContent className="p-3 sm:p-4">
                    <div className="flex items-start space-x-3 sm:space-x-4">
                      <RadioGroupItem value="processing-centers" id="milling" className="mt-1" />
                      <div className="flex-1 min-w-0">
                        <Label htmlFor="milling" className="text-base sm:text-lg font-semibold cursor-pointer">Milling & Drilling</Label>
                        <p className="text-xs sm:text-sm text-gray-400 mt-1">Lock holes, handle holes, and hardware placement for complete assembly</p>
                        <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                          <Badge variant="secondary" className="text-xs">Lock Holes</Badge>
                          <Badge variant="secondary" className="text-xs">Hardware Placement</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </RadioGroup>
          </motion.div>
        );
      case 'automation':
        return (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="space-y-6"
          >
            <div className="text-center">
              <Cpu className="h-12 w-12 text-almona-orange mx-auto mb-4" />
              <h3 className="text-2xl font-bold mb-2">Automation Level</h3>
              <p className="text-gray-400">What level of automation fits your production needs?</p>
            </div>
            <RadioGroup value={answers.automation} onValueChange={(v) => handleValueChange('automation', v)}>
              <div className="grid gap-4">
                <Card 
                  className={`cursor-pointer transition-all ${answers.automation === 'manual' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('automation', 'manual')}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-4">
                      <RadioGroupItem value="manual" id="manual" />
                      <div className="flex-1">
                        <Label htmlFor="manual" className="text-lg font-semibold cursor-pointer">Manual Operation</Label>
                        <p className="text-sm text-gray-400 mt-1">Operator-controlled machines for custom and small-batch production</p>
                        <div className="flex gap-2 mt-2">
                          <Badge variant="secondary">Operator Control</Badge>
                          <Badge variant="secondary">Custom Work</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card 
                  className={`cursor-pointer transition-all ${answers.automation === 'automatic' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('automation', 'automatic')}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-4">
                      <RadioGroupItem value="automatic" id="automatic" />
                      <div className="flex-1">
                        <Label htmlFor="automatic" className="text-lg font-semibold cursor-pointer">Semi-Automatic</Label>
                        <p className="text-sm text-gray-400 mt-1">Automated processes with operator supervision for medium-scale production</p>
                        <div className="flex gap-2 mt-2">
                          <Badge variant="secondary">Automated Process</Badge>
                          <Badge variant="secondary">Operator Supervised</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card 
                  className={`cursor-pointer transition-all ${answers.automation === 'cnc' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('automation', 'cnc')}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-4">
                      <RadioGroupItem value="cnc" id="cnc" />
                      <div className="flex-1">
                        <Label htmlFor="cnc" className="text-lg font-semibold cursor-pointer">CNC & Fully Automatic</Label>
                        <p className="text-sm text-gray-400 mt-1">Computer-controlled precision for high-volume, consistent production</p>
                        <div className="flex gap-2 mt-2">
                          <Badge variant="secondary">CNC Control</Badge>
                          <Badge variant="secondary">High Precision</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </RadioGroup>
          </motion.div>
        );
      case 'production':
        return (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="space-y-6"
          >
            <div className="text-center">
              <TrendingUp className="h-12 w-12 text-almona-orange mx-auto mb-4" />
              <h3 className="text-2xl font-bold mb-2">Production Scale</h3>
              <p className="text-gray-400">What is your expected production volume?</p>
            </div>
            <RadioGroup value={answers.production} onValueChange={(v) => handleValueChange('production', v)}>
              <div className="grid gap-4">
                <Card 
                  className={`cursor-pointer transition-all ${answers.production === 'small-scale' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('production', 'small-scale')}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-4">
                      <RadioGroupItem value="small-scale" id="small-scale" />
                      <div className="flex-1">
                        <Label htmlFor="small-scale" className="text-lg font-semibold cursor-pointer">Small Scale (1-50 units/day)</Label>
                        <p className="text-sm text-gray-400 mt-1">Perfect for custom work, repairs, and small workshops</p>
                        <div className="flex gap-2 mt-2">
                          <Badge variant="secondary">Custom Work</Badge>
                          <Badge variant="secondary">Flexible</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card 
                  className={`cursor-pointer transition-all ${answers.production === 'medium-scale' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('production', 'medium-scale')}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-4">
                      <RadioGroupItem value="medium-scale" id="medium-scale" />
                      <div className="flex-1">
                        <Label htmlFor="medium-scale" className="text-lg font-semibold cursor-pointer">Medium Scale (50-200 units/day)</Label>
                        <p className="text-sm text-gray-400 mt-1">Ideal for regional manufacturers and growing businesses</p>
                        <div className="flex gap-2 mt-2">
                          <Badge variant="secondary">Regional Scale</Badge>
                          <Badge variant="secondary">Growing Business</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
                <Card 
                  className={`cursor-pointer transition-all ${answers.production === 'high-volume' ? 'ring-2 ring-almona-orange bg-almona-orange/10' : 'hover:bg-gray-800/50'}`}
                  onClick={() => handleValueChange('production', 'high-volume')}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center space-x-4">
                      <RadioGroupItem value="high-volume" id="high-volume" />
                      <div className="flex-1">
                        <Label htmlFor="high-volume" className="text-lg font-semibold cursor-pointer">High Volume (200+ units/day)</Label>
                        <p className="text-sm text-gray-400 mt-1">Production line solutions for large-scale manufacturing</p>
                        <div className="flex gap-2 mt-2">
                          <Badge variant="secondary">Production Line</Badge>
                          <Badge variant="secondary">High Volume</Badge>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
          </div>
            </RadioGroup>
          </motion.div>
        );
      case 'results':
        return (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="space-y-6"
          >
            <div className="text-center">
              <Award className="h-10 w-10 sm:h-12 sm:w-12 text-almona-orange mx-auto mb-4" />
              <h3 className="text-xl sm:text-2xl font-bold mb-2">Recommended Machines</h3>
              <p className="text-gray-400 text-sm sm:text-base">Based on your requirements, here are our top recommendations</p>
            </div>

            {/* Summary Report */}
            <Card className="bg-gray-800/50 border-gray-600">
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-4">
                  <h4 className="text-lg font-semibold flex items-center gap-2">
                    <FileText className="h-5 w-5 text-almona-orange" />
                    Selection Summary
                  </h4>
                  <Button 
                    size="sm" 
                    variant="outline"
                    onClick={handleExportSummary}
                    className="flex items-center gap-2"
                  >
                    <Download className="h-4 w-4" />
                    Export TXT
                  </Button>
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-sm">
                  <div>
                    <span className="text-gray-400">Material:</span>
                    <p className="font-medium capitalize">{answers.material}</p>
                  </div>
                  <div>
                    <span className="text-gray-400">Application:</span>
                    <p className="font-medium capitalize">{answers.application.replace('-', ' ')}</p>
                  </div>
                  <div>
                    <span className="text-gray-400">Automation:</span>
                    <p className="font-medium capitalize">{answers.automation}</p>
                  </div>
                  <div>
                    <span className="text-gray-400">Production:</span>
                    <p className="font-medium capitalize">{answers.production.replace('-', ' ')}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <div className="grid grid-cols-1 gap-3 sm:gap-4 max-h-[40vh] sm:max-h-[50vh] overflow-y-auto">
              {recommendations.length > 0 ? recommendations.map(machine => (
                <Card key={machine.id} className="hover:bg-gray-800/50 transition-colors">
                  <CardContent className="p-3 sm:p-4">
                    <div className="flex items-start space-x-3 sm:space-x-4">
                      <div className="w-12 h-12 sm:w-16 sm:h-16 bg-gray-700 rounded-lg flex items-center justify-center flex-shrink-0">
                        <Settings className="h-6 w-6 sm:h-8 sm:w-8 text-almona-orange" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <h4 className="font-semibold text-base sm:text-lg">{machine.name}</h4>
                        <p className="text-xs sm:text-sm text-gray-400 mt-1 line-clamp-2">{machine.description}</p>
                        <div className="flex flex-wrap gap-1 sm:gap-2 mt-2">
                          {machine.tags?.slice(0, 3).map(tag => (
                            <Badge key={tag} variant="secondary" className="text-xs">{tag}</Badge>
                          ))}
                        </div>
                      </div>
                      <div className="flex flex-col gap-2 flex-shrink-0">
                        <Button 
                          size="sm" 
                          className="bg-almona-orange hover:bg-almona-orange-dark text-xs sm:text-sm"
                          onClick={() => handleDownloadSpecs(machine)}
                        >
                          <Download className="h-3 w-3 sm:h-4 sm:w-4 mr-1" />
                          View Details
                        </Button>
                        <Button 
                          size="sm" 
                          variant="outline"
                          className="text-xs sm:text-sm"
                          onClick={() => handleAddToQuote(machine)}
                        >
                          <ShoppingCart className="h-3 w-3 sm:h-4 sm:w-4 mr-1" />
                          Add to Quote
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )) : (
                <Card>
                  <CardContent className="p-8 text-center">
                    <Sparkles className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                    <h4 className="text-lg font-semibold mb-2">No Perfect Match Found</h4>
                    <p className="text-gray-400 mb-4">Let our experts help you find the right solution for your specific needs.</p>
                    <Button asChild className="bg-almona-orange hover:bg-almona-orange-dark">
                      <Link to="/contact">
                        Contact Our Experts
                      </Link>
                    </Button>
                  </CardContent>
                </Card>
              )}
            </div>
          </motion.div>
        );
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-[95vw] max-w-4xl h-[90vh] max-h-[800px] overflow-hidden flex flex-col">
        <DialogHeader className="border-b border-gray-700 pb-4 flex-shrink-0">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="flex-1">
              <DialogTitle className="text-xl sm:text-2xl font-bold flex items-center gap-2">
                <Sparkles className="h-5 w-5 sm:h-6 sm:w-6 text-almona-orange" />
                <span className="truncate">Machine Recommendation Wizard</span>
              </DialogTitle>
              <p className="text-gray-400 mt-1 text-sm sm:text-base">Find the perfect machinery for your aluminum & UPVC window/door production</p>
            </div>
            <div className="text-sm text-gray-400 flex-shrink-0">
              Step {currentStepIndex + 1} of {steps.length}
            </div>
          </div>
          
          {/* Progress Bar */}
          <div className="mt-4">
            <div className="flex items-center justify-between mb-2 overflow-x-auto">
              {steps.map((stepItem, index) => {
                const Icon = stepItem.icon;
                const isCompleted = index < currentStepIndex;
                const isCurrent = index === currentStepIndex;
                
                return (
                  <div key={stepItem.id} className="flex items-center flex-shrink-0">
                    <div className={`flex items-center justify-center w-6 h-6 sm:w-8 sm:h-8 rounded-full border-2 transition-all ${
                      isCompleted 
                        ? 'bg-almona-orange border-almona-orange text-white' 
                        : isCurrent 
                        ? 'border-almona-orange text-almona-orange' 
                        : 'border-gray-600 text-gray-400'
                    }`}>
                      {isCompleted ? (
                        <CheckCircle className="h-3 w-3 sm:h-4 sm:w-4" />
                      ) : (
                        <Icon className="h-3 w-3 sm:h-4 sm:w-4" />
                      )}
                    </div>
                    {index < steps.length - 1 && (
                      <div className={`w-6 sm:w-12 h-0.5 mx-1 sm:mx-2 transition-all ${
                        isCompleted ? 'bg-almona-orange' : 'bg-gray-600'
                      }`} />
                    )}
                  </div>
                );
              })}
            </div>
            <div className="text-center">
              <span className="text-xs sm:text-sm font-medium text-almona-orange">
                {steps[currentStepIndex]?.title}
              </span>
            </div>
          </div>
        </DialogHeader>
        
        <div className="flex-1 overflow-y-auto py-4 sm:py-6 px-2 sm:px-0">
          <AnimatePresence mode="wait">
        {renderStep()}
          </AnimatePresence>
        </div>
        
        <DialogFooter className="border-t border-gray-700 pt-4 flex-shrink-0">
          <div className="flex flex-col sm:flex-row justify-between w-full gap-3">
            <Button 
              variant="outline" 
              onClick={prevStep}
              disabled={currentStepIndex === 0}
              className="flex items-center gap-2 w-full sm:w-auto"
            >
              <ArrowLeft className="h-4 w-4" />
              Back
            </Button>
            
            <div className="flex gap-2 w-full sm:w-auto">
              {step === 'results' ? (
                <Button variant="outline" onClick={resetWizard} className="flex items-center gap-2 flex-1 sm:flex-none">
                  <Sparkles className="h-4 w-4" />
                  Start Over
                </Button>
              ) : (
                <Button 
                  onClick={nextStep}
                  disabled={!answers[step as keyof WizardAnswers]}
                  className="bg-almona-orange hover:bg-almona-orange-dark flex items-center gap-2 flex-1 sm:flex-none"
                >
                  <span className="hidden sm:inline">
                    {currentStepIndex === steps.length - 2 ? 'Get Recommendations' : 'Next'}
                  </span>
                  <span className="sm:hidden">
                    {currentStepIndex === steps.length - 2 ? 'Get Results' : 'Next'}
                  </span>
                  <ArrowRight className="h-4 w-4" />
                </Button>
              )}
            </div>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default MachineRecommendationWizard;
