import { DEFAULT_GRID } from '@/components/fabricator/measuringConstants';
import { EGYPTIAN_GRID_STANDARDS } from '@/data/egyptianGridStandards';
import { WindowGrid } from '@/types/fabricator';
import { useEffect, useRef, useState } from 'react';
import { useDebouncedCallback } from 'use-debounce';

interface UseEgyptianPredictiveGridProps {
  width: number;
  height: number;
  windowType: string;
  isGridLocked: boolean; // If true, never predict
}

interface UseEgyptianPredictiveGridResult {
  suggestedGrid: WindowGrid | null;
  isPredicting: boolean;
  predictionReason: string | null;
}

/**
 * Hook to predict standard Egyptian grid layouts based on dimensions.
 * 
 * @param width - Manufacturing width in mm
 * @param height - Manufacturing height in mm
 * @param windowType - 'sliding', 'casement', etc.
 * @param isGridLocked - Prevents overrides if user manually edited grid
 */
export const useEgyptianPredictiveGrid = ({
  width,
  height,
  windowType,
  isGridLocked
}: UseEgyptianPredictiveGridProps): UseEgyptianPredictiveGridResult => {
  const [suggestedGrid, setSuggestedGrid] = useState<WindowGrid | null>(null);
  const [predictionReason, setPredictionReason] = useState<string | null>(null);
  const [isPredicting, setIsPredicting] = useState(false);

  // Store last predicted dimensions to avoid re-predicting same inputs
  const lastPredictedRef = useRef<{w: number, h: number, t: string, l: boolean} | null>(null);

  const predict = useDebouncedCallback(() => {
    if (isGridLocked) {
      setIsPredicting(false);
      return;
    }

    if (!width || !height || width <= 0 || height <= 0) {
      setIsPredicting(false);
      return;
    }

    // Performance optimization: Skip if same inputs
    if (
      lastPredictedRef.current &&
      lastPredictedRef.current.w === width &&
      lastPredictedRef.current.h === height &&
      lastPredictedRef.current.t === windowType &&
      lastPredictedRef.current.l === isGridLocked
    ) {
        setIsPredicting(false);
        return;
    }
    
    lastPredictedRef.current = { w: width, h: height, t: windowType, l: isGridLocked };

    const typeLower = windowType.toLowerCase();
    
    // Default to existing grid structure or baseline
    let cols: number = DEFAULT_GRID.DEFAULT_COLS;
    const rows: number = DEFAULT_GRID.DEFAULT_ROWS;
    let reason = '';

    // Logic: Sliding
    if (typeLower.includes('sliding')) {
        if (width <= EGYPTIAN_GRID_STANDARDS.SLIDING.THRESHOLDS.TWO_PANEL_LIMIT) {
            cols = 2;
            reason = `Width ${width}mm fits standard 2-panel sliding (<${EGYPTIAN_GRID_STANDARDS.SLIDING.THRESHOLDS.TWO_PANEL_LIMIT}mm)`;
        } else if (width <= EGYPTIAN_GRID_STANDARDS.SLIDING.THRESHOLDS.THREE_PANEL_LIMIT) {
            cols = 3; 
            reason = `Width ${width}mm suggests 3-panel sliding (or 2-panel Jumbo)`;
        } else {
            cols = 4;
            reason = `Width ${width}mm requires 4-panel sliding (> ${EGYPTIAN_GRID_STANDARDS.SLIDING.THRESHOLDS.THREE_PANEL_LIMIT}mm)`;
        }
    } 
    // Logic: Casement/Turn
    else if (typeLower.includes('casement') || typeLower.includes('turn')) {
        if (width <= EGYPTIAN_GRID_STANDARDS.CASEMENT.THRESHOLDS.SINGLE_SASH_LIMIT) {
             cols = 1;
             reason = `Width ${width}mm fits single sash (<${EGYPTIAN_GRID_STANDARDS.CASEMENT.THRESHOLDS.SINGLE_SASH_LIMIT}mm)`;
        } else {
            cols = 2; // French window
            reason = `Width ${width}mm suggests double sash (> ${EGYPTIAN_GRID_STANDARDS.CASEMENT.THRESHOLDS.SINGLE_SASH_LIMIT}mm)`;
        }
    }
    
    // Construct the new grid object
    let colWidths = Array(cols).fill(1); // Default symmetric (1:1...)

    // Apply Specific Symmetry Rules (Phase 3 Option A)
    if (typeLower.includes('sliding') && cols === 3) {
        colWidths = [...EGYPTIAN_GRID_STANDARDS.SLIDING.RATIOS.THREE_PANEL_SYMMETRIC]; // [1, 2, 1]
        reason += ' (Preferred 1:2:1 QHQ symmetry)';
    }

    const newGrid: WindowGrid = {
        rows,
        cols,
        cells: [], // Cells would be regenerated by the SmartDrawCanvas based on rows/cols
        colWidths, 
        rowHeights: Array(rows).fill(1)
    };

    // Simulate cell generation for completeness (simplified)
    for(let r=0; r<rows; r++) {
        for(let c=0; c<cols; c++) {
            newGrid.cells.push({
                id: `p-${r}-${c}`,
                row: r,
                col: c,
                type: typeLower.includes('sliding') ? 'sliding' : 'sash'
            });
        }
    }

    setSuggestedGrid(newGrid);
    setPredictionReason(reason);
    setIsPredicting(false);

  }, 500); // 500ms debounce

  // Trigger prediction when inputs change
  useEffect(() => {
    if (isGridLocked) return;
    setIsPredicting(true);
    predict();
  }, [width, height, windowType, isGridLocked, predict]);

  return { suggestedGrid, isPredicting, predictionReason };
};
