#!/bin/bash
# scripts/deploy-backend-render.sh
# Render deployment instructions

echo "🚀 Deploying Backend to Render"
echo "==============================="
echo ""
echo "📋 Manual Steps (Render Dashboard):"
echo ""
echo "1. Go to https://render.com"
echo "2. Sign in with GitHub"
echo "3. Click 'New' → 'Web Service'"
echo "4. Connect GitHub repository: almona-portfolio-forge"
echo "5. Configure:"
echo "   - Name: almona-backend"
echo "   - Branch: main"
echo "   - Root Directory: python_backend"
echo "   - Environment: Docker"
echo "   - Dockerfile Path: Dockerfile.realistic"
echo "   - Health Check Path: /health"
echo ""
echo "6. Set Environment Variables:"
echo "   DATABASE_URL=postgresql://..."
echo "   REDIS_URL=redis://..."
echo "   SUPABASE_URL=https://your-project.supabase.co"
echo "   SUPABASE_KEY=your_service_role_key"
echo "   SECRET_KEY=your_secret_key"
echo "   TZ=Africa/Cairo"
echo "   LANG=ar_EG.UTF-8"
echo "   LC_ALL=ar_EG.UTF-8"
echo ""
echo "7. Add PostgreSQL Database:"
echo "   - New → PostgreSQL"
echo "   - Copy DATABASE_URL to environment variables"
echo ""
echo "8. Deploy!"
echo ""
echo "✅ After deployment:"
echo "   - Backend URL: https://your-app.onrender.com"
echo "   - Update Vercel: VITE_API_URL=https://your-app.onrender.com"
echo ""

