services:
  python:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:rw
      - ./uploads:/app/uploads:rw
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A core.celery_app worker --loglevel=info
    volumes:
      - ./:/app:rw
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

volumes:
  redis_data:
